# @package _global_

obs:
  obs_dict:
    actor_obs: [dof_pos, dof_vel, ref_dof_pos, actions]
    critic_obs: [dof_pos, dof_vel, ref_dof_pos, actions]

  history_length:
    actor_obs: 1
    critic_obs: 1

  obs_scales:
    dof_pos: 1.0
    dof_vel: 0.05
    ref_dof_pos: 1.0
    actions: 1.0

  noise_scales:
    dof_pos: 0.0
    dof_vel: 0.0
    ref_dof_pos: 0.0
    actions: 0.0

  add_noise: False

  obs_dims:
    - dof_pos: ${robot.dof_obs_size}
    - dof_vel: ${robot.dof_obs_size}
    - ref_dof_pos: ${robot.dof_obs_size}
    - actions: ${robot.actions_dim}

  post_compute_config: {}
